FROM registry.access.redhat.com/ubi9/ubi-minimal:9.6

WORKDIR /work/

COPY target/*-runner /work/application

RUN chmod 775 /work/application \
    && chown 1001:root /work/application

EXPOSE 8082

ENV QUARKUS_HTTP_HOST=0.0.0.0
ENV QUARKUS_HTTP_PORT=8082

USER 1001

ENTRYPOINT ["./application"]
